"""Hermetic abstract-grounded corpus for the focused-panel study flow."""

from agora.focused.models import ExpPaper

DEMO_RESEARCH_QUESTIONS = [
    "Does broad-spectrum use raise resistance enough to matter at population level?",
    "Does it harm the patient's own flora in ways that outlast the infection?",
    "When does speed to cure outweigh both?",
]


def _paper(
    paper_id: str,
    title: str,
    year: int,
    venue: str,
    authors: list[str],
    scope: str,
    explanation: str,
    approach: str,
    significance: str,
) -> ExpPaper:
    sentences = [scope, explanation, approach, significance]
    return ExpPaper(
        id=paper_id,
        title=title,
        abstract=" ".join(sentences),
        abstract_sentences=sentences,
        year=year,
        venue=venue,
        authors=authors,
    )


DEMO_PAPERS: list[ExpPaper] = [
    _paper(
        "p1",
        "Broad-spectrum overuse and the rise of resistance genes",
        2021,
        "The Lancet Infectious Diseases",
        ["R. Okonkwo", "M. Halvorsen", "J. Pereira"],
        "This study examines cumulative broad-spectrum exposure across fourteen hospitals.",
        "Longer exposure selects for a higher prevalence of resistance genes.",
        "A longitudinal hospital cohort links antibiotic-days with resistome measurements.",
        "The result makes cumulative resistance a population-level cost of routine broad prescribing.",
    ),
    _paper(
        "p2",
        "Gut microbiome disruption after antibiotic therapy",
        2020,
        "Nature Microbiology",
        ["S. Lindqvist", "A. Bhattacharya", "T. Moreau"],
        "This study follows adult patients' gut microbiomes during and after broad-spectrum therapy.",
        "Broad agents deplete commensal diversity and recovery remains incomplete after treatment.",
        "Repeated 16S sequencing measures within-patient diversity trajectories.",
        "Persistent dysbiosis makes treatment effects beyond pathogen clearance clinically consequential.",
    ),
    _paper(
        "p3",
        "Empiric broad-spectrum therapy and ICU mortality",
        2019,
        "Critical Care Medicine",
        ["D. Ferreira", "K. Nwosu", "H. Yamada", "L. Grant"],
        "This study covers adults with suspected sepsis in intensive care.",
        "Early broad coverage reduces the chance that the infecting pathogen is initially untreated.",
        "A severity-adjusted ICU cohort compares early coverage with thirty-day mortality.",
        "The association supports prioritizing adequate immediate coverage when delay is life-threatening.",
    ),
    _paper(
        "p4",
        "Rapid diagnostics enable narrow-spectrum choice",
        2023,
        "Journal of Clinical Microbiology",
        ["P. Venkatesan", "E. Cardoso"],
        "This study examines hospitalized infections eligible for rapid pathogen identification.",
        "Earlier identification reduces uncertainty and enables safe antibiotic de-escalation.",
        "A prospective implementation study compares time to identification and time to narrowing.",
        "Rapid diagnosis can preserve acute safety without accepting prolonged broad exposure.",
    ),
    _paper(
        "p5",
        "Population-level cost of broad prescribing",
        2020,
        "Clinical Infectious Diseases",
        ["M. Abadi", "R. Sorensen", "N. Achebe"],
        "This analysis covers short-term treatment benefit and long-run societal resistance costs.",
        "Each broad prescription adds selection pressure whose costs accumulate beyond the treated patient.",
        "A decision model combines cure benefits, resistance prevalence, and downstream treatment costs.",
        "Long-run externalities can outweigh the immediate expected benefit of routine broad prescribing.",
    ),
    _paper(
        "p6",
        "Antibiotic stewardship programs reduce resistance rates",
        2020,
        "Infection Control and Hospital Epidemiology",
        ["C. Whitfield", "J. Ramos", "A. Iyer"],
        "This study evaluates hospital wards adopting an antibiotic stewardship programme.",
        "Reducing unnecessary broad prescriptions lowers ward-level selection pressure.",
        "A controlled before-and-after analysis tracks prescribing and resistance rates.",
        "Institutional governance can reduce resistance without relying on isolated clinician choices.",
    ),
    _paper(
        "p7",
        "Horizontal gene transfer under sub-inhibitory exposure",
        2019,
        "mBio",
        ["L. Petrov", "S. Adeyemi", "F. Marchetti"],
        "This study examines bacterial communities exposed to sub-inhibitory antibiotics.",
        "Low-dose exposure accelerates plasmid-mediated horizontal transfer of resistance genes.",
        "Laboratory assays quantify transfer rates across controlled exposure levels.",
        "Even incomplete antibiotic exposure may propagate resistance beyond directly selected mutants.",
    ),
    _paper(
        "p8",
        "Commensal depletion and C. difficile risk",
        2019,
        "Gastroenterology",
        ["B. Novak", "H. Osei", "M. Lindholm"],
        "This cohort follows patients after broad therapy to measure colonization resistance.",
        "Commensal depletion removes ecological barriers to Clostridioides difficile infection.",
        "Microbiome profiles are linked prospectively to subsequent infection incidence.",
        "Protecting commensals is a safety outcome rather than a secondary biological curiosity.",
    ),
    _paper(
        "p9",
        "Empiric therapy duration and resistance emergence",
        2021,
        "Journal of Antimicrobial Chemotherapy",
        ["T. Sandoval", "R. Kaur", "E. Bjornsson"],
        "This study covers hospitalized patients receiving empiric broad therapy for varying durations.",
        "Each additional exposure day increases selection for newly resistant isolates.",
        "A multivariable cohort model estimates resistance odds per additional treatment day.",
        "Duration is a modifiable driver even when broad initial coverage is justified.",
    ),
    _paper(
        "p10",
        "Time-to-cure with early broad coverage",
        2021,
        "Chest",
        ["A. Duarte", "M. Okafor", "S. Vaughn"],
        "This study examines adults treated empirically for serious bacterial infection.",
        "Broader initial coverage increases the probability of matching the pathogen immediately.",
        "A matched cohort compares time to clinical cure across initial treatment strategies.",
        "A roughly two-day cure advantage may justify temporary breadth in high-risk cases.",
    ),
    _paper(
        "p11",
        "Narrow-spectrum sparing of gut flora",
        2021,
        "Gut Microbes",
        ["J. Halloran", "N. Petrosyan", "K. Adeleke"],
        "This trial covers patients with identified pathogens eligible for targeted antibiotics.",
        "Narrow agents spare commensal organisms while retaining pathogen-directed activity.",
        "A comparative treatment study measures clinical response and microbial diversity.",
        "Targeted therapy can preserve efficacy while reducing ecological harm when diagnosis is known.",
    ),
    _paper(
        "p12",
        "Under-treatment risk in sepsis",
        2019,
        "Intensive Care Medicine",
        ["G. Rasmussen", "P. Chandrasekhar", "L. Mbeki"],
        "This study focuses on patients with severe sepsis before pathogen identity is available.",
        "Delayed adequate coverage permits uncontrolled infection and sharply raises mortality.",
        "A time-to-treatment cohort relates coverage delay to risk-adjusted mortality.",
        "The asymmetric immediate danger supports broad first doses for unstable patients.",
    ),
    _paper(
        "p13",
        "Pediatric antibiotic exposure and later allergy",
        2022,
        "JAMA Pediatrics",
        ["E. Lindgren", "R. Oyelaran", "D. Ferrante"],
        "This study follows children exposed to broad antibiotics during infancy.",
        "Early microbiome disruption may alter immune development and later allergy risk.",
        "A birth cohort links prescription records with childhood allergy incidence.",
        "Potential developmental effects extend the relevant harm horizon beyond the treated infection.",
    ),
    _paper(
        "p14",
        "Agricultural antibiotic use and community resistance",
        2020,
        "Environmental Health Perspectives",
        ["M. Szabo", "T. Aguilar", "J. Nakamura"],
        "This ecological study compares regions with different levels of agricultural antibiotic use.",
        "Agricultural selection pressure contributes to resistant organisms carried into communities.",
        "Regional usage estimates are associated with surveillance measures of resistance carriage.",
        "Effective stewardship may need to cross the boundary between farms and clinical care.",
    ),
    _paper(
        "p15",
        "Procalcitonin-guided antibiotic cessation",
        2022,
        "The Lancet Respiratory Medicine",
        ["S. Beaulieu", "A. Rahimi", "C. Nwachukwu", "P. Holm"],
        "This trial includes hospitalized patients whose response can be monitored with procalcitonin.",
        "Biomarker decline identifies when continued antibiotic exposure is unlikely to add benefit.",
        "A randomized stopping-rule trial compares antibiotic-days and adverse outcomes.",
        "Guided cessation reduces exposure without sacrificing measured clinical safety.",
    ),
    _paper(
        "p16",
        "Delayed prescribing in primary care",
        2019,
        "BMJ",
        ["H. Fitzgerald", "M. Ibrahim", "R. Delacroix"],
        "This study covers mild infections managed in primary care with reliable follow-up.",
        "A wait-and-see prescription changes expectations and avoids unnecessary immediate use.",
        "A pragmatic trial compares dispensing, symptom duration, and complication rates.",
        "Many low-risk infections can avoid antibiotics without increasing complications.",
    ),
    _paper(
        "p17",
        "Combination therapy and resistance suppression",
        2021,
        "Antimicrobial Agents and Chemotherapy",
        ["K. Vasquez", "L. Onyeka", "A. Steiner"],
        "This study examines difficult infections exposed to single-drug or two-drug regimens.",
        "Simultaneous mechanisms lower the probability that one resistant mutant escapes treatment.",
        "Laboratory and animal experiments measure resistant-mutant emergence under each regimen.",
        "Combination therapy may trade additional toxicity and cost for slower resistance evolution.",
    ),
    _paper(
        "p18",
        "Phage therapy as a narrow alternative",
        2023,
        "Cell Host and Microbe",
        ["N. Kowalski", "J. Baptiste", "S. Ramanathan"],
        "This study covers resistant infections with isolates that can be matched to phage cocktails.",
        "Pathogen-specific phages clear target bacteria while sparing commensal organisms.",
        "A compassionate-use series records clearance, safety, and microbiome preservation.",
        "Target-specific alternatives could displace broad drugs when matching is feasible.",
    ),
    _paper(
        "p19",
        "Antibiotics and chemotherapy response via microbiome",
        2022,
        "Science",
        ["A. Lindeberg", "M. Oduya", "T. Bergeron", "R. Ishikawa"],
        "This study follows cancer patients receiving antibiotics before immunotherapy.",
        "Antibiotic-driven microbiome shifts may blunt immune responses to cancer treatment.",
        "A clinical cohort relates pre-treatment exposure and microbiome profiles to response.",
        "Antibiotic harm may include reduced effectiveness of an otherwise unrelated therapy.",
    ),
    _paper(
        "p20",
        "Machine-learning prediction of resistant infection",
        2023,
        "Nature Medicine",
        ["C. Aluko", "D. Marchand", "S. Krishnan"],
        "This study covers patients needing empiric therapy before culture results arrive.",
        "Patient-specific resistance prediction can narrow coverage without ignoring under-treatment risk.",
        "A multisite EHR model is validated for resistance discrimination and transfer.",
        "Reliable prediction could personalize empiric breadth instead of applying one policy to everyone.",
    ),
]
